### ISSUE TITLE
Add Firefox support

### ISSUE THREAD

**Issue by MBakirci** [DivMagicCom/DivMagic#1]
### Add Firefox support 

I would like to request a new feature for the extension that would add support for Firefox. Currently, the extension is only available for Chrome users, but as a Firefox user, I would love to have the same functionality.

**Comment by RealBrianH** [comment]
Firefox extension has been released!

https://addons.mozilla.org/en-US/firefox/addon/divmagic/

It has the same code as the Chrome one so the output will be the same most of the time.

There are a few edge cases that I've found where some Mozilla specific styles might not get converted the same as Chrome. I'll work on those too.
