### ISSUE TITLE
Add another way to trigger it?

### ISSUE THREAD

**Issue by yanggggjie** [DivMagicCom/DivMagic#2]
Hi,  the very cool extension author 👋🏼.
I can't copy buttons, cause when I click a button it's events triggered install of copy itself.
And I can  copy a block that contains the button, then I find it out from the pasted codes.
Would you like to add another way to trigger copy, such as  keyboard shortcut or something.

**Comment by RealBrianH** [comment]
Thanks for the issue, I will make an update for that

**Comment by RealBrianH** [comment]
A new version has been published now. You can use v1.0.3 (May 27 update).

You can press the "D" button while hovering over an element to copy the style. This way you don't have to click buttons and trigger them while copying the style.
