### ISSUE TITLE
Firefox version does not exist in extensions any more

### ISSUE THREAD

**Issue by tylkomat** [DivMagicCom/DivMagic#3]
https://addons.mozilla.org/en-US/firefox/addon/divmagic/

**Comment by RealBrianH** [comment]
It got removed by the Firefox team. I'm working on making the changes they requested. It will be available again after they review it.

**Comment by RealBrianH** [comment]
Firefox version is available again: https://addons.mozilla.org/en-US/firefox/addon/divmagic/
