### ISSUE TITLE
Responsive elements

### ISSUE THREAD

**Issue by hoyere** [DivMagicCom/DivMagic#5]
Is there any support for getting the responsive elements or the break points of an element and that div code? Or do i need to adjust the window size and grab several variations with DivMagic?

Or am I coming at this the wrong way, I have never been a strong frontend guy, so maybe there is a technique I am just not aware of....

Thank you, sorry for posting in issues, not sure where else to ask

**Comment by RealBrianH** [comment]
When you set the [Media Query](https://divmagic.com/docs/settings/media-query) setting On, DivMagic should automatically get all the break points for an element.

If you use Tailwind CSS option, it will put them into the class names. If you use any other CSS option, it will put them under the `<style> @media`

For example, this is Airbnb's footer: https://divmagic.com/studio/c/1E4SLhRD0f

The break points are put under the `@media` tags inside `<style>`

Please let me know if this helps!
